### ISSUE TITLE
sample downloader: 取得失敗 UTPC 2011

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#106]
http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=2259
https://beta.atcoder.jp/contests/utpc2011/tasks/utpc2011_1

AOJ経由でもAtCoder経由でもだめ そもそもAtCoder側は既に壊れてるし

**Comment by kawacchu** [comment]
This contest's HTML seems different from any other contests in AtCoder.
In my work on #573, I re-found this issue.

We can solve this issue by using `soup.find_all('pre', 'literal-block')`.

**Comment by fukatani** [comment]
Resolved by #581
