### ISSUE TITLE
download: broken at Yukicoder No.750,751

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#192]
https://yukicoder.me/problems/no/750
https://yukicoder.me/problems/no/751

**Comment by kawacchu** [comment]
[https://yukicoder.me/problems/no/750](https://yukicoder.me/problems/no/750)
[https://yukicoder.me/problems/no/751](https://yukicoder.me/problems/no/751)

I checked the HTML source.
In no.750 and no.751, I found that the `<br>` tag was written within the `<pre>` tag.

Ex) no.750 サンプル1
 `<pre>6<br />1 1<br />7 4<br />0 5<br />1 3<br />-8 9<br />5 1</pre>`

I guess that is the cause of the bug.

**Comment by kmyk** [comment]
@kawacchu If you're interested in, please make the pull request!

**Comment by kawacchu** [comment]
@kmyk @fukatani 

Although I'm a beginner in this field, I will do my best!
When I'm in trouble, I ask for your advice!

**Comment by kawacchu** [comment]
I am going to prepare my pull request!
Which branch is preferable, `master` or `develop`?

My pull request will solve this issue, but will remain unexpected behavior for the user in some problems. (although I have never seen in real environment.)

**Comment by fukatani** [comment]
Please create branch from `master`. I removed `develop` branch.

> My pull request will solve this issue, but the unexpected behavior for the user will remain in some problems. (although I have never seen it in a real environment.)

Unittest and code review reduce such a risk, let's do our best together!

**Comment by kawacchu** [comment]
OK, thanks!

**Comment by kmyk** [comment]
This issue is fixed by https://github.com/kmyk/online-judge-tools/pull/552, and the remaining problem is opened as https://github.com/kmyk/online-judge-tools/issues/553.
Thank you, @kawacchu.
