### ISSUE TITLE
Python>=3.6以上のみ対応でしょうか？

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#212]
```
    msgtags: List[str] = []
           ^
SyntaxError: invalid syntax
```
というエラーがでるようになりました。
ローカル変数の型アノテーションが3.6以降なんでしたっけ？
Python 3.5.2 で動かしています。

**Comment by kmyk** [comment]
直せませんでした。 (https://github.com/kmyk/online-judge-tools/pull/214)
そもそも以前から 3.5 以下ではきちんと動いていなかったみたいです。

なので、現状は 3.6 以上のみ対応というのが返事になります。

**Comment by fukatani** [comment]
ご回答ありがとうございます。
私の環境で、Python3.5対応できないか少し試してみます。
あと、mypy入ってないのがエラーの原因だったかもしれません。調査します。
