### ISSUE TITLE
improve code generator

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#252]
-   [ ] サンプルと突き合わせての型の判断
-   [ ] 出力形式の判定 (`Yes` / `No` とか)
-   [ ] 出力部分のコード生成
-   [ ] MODの値の取得
-   [ ] 制約の取得
-   [ ] 乱択ケースの生成
-   [ ] 問題文を解析してグラフをいい感じに受け取る
-   [ ] 解析精度の向上
-   [ ] 出力先言語の選択を可能に
-   [ ] 対応サービスの増加

**Comment by kmyk** [comment]
現状の解析失敗報告:

-   #47 https://beta.atcoder.jp/contests/abc071/tasks/arc081_b
-   #74 http://kupc2017.contest.atcoder.jp/tasks/kupc2017_i
-   #142 https://beta.atcoder.jp/contests/dwacon2018-final/tasks/dwacon2018_final_a
-   #142 https://beta.atcoder.jp/contests/dwacon2018-final/tasks/dwacon2018_final_b

**Comment by kmyk** [comment]
`出力先言語の選択を可能に` 忘れてたので足した

**Comment by kmyk** [comment]
既存のコードがスパゲッティと化してることからただそのまま既にあるものを拡張するのは大変で、大きめのrefactoringが必要です。
またこの部分は https://github.com/kyuridenamida/atcoder-tools が一歩先を行ってることが知られています。
このため選択肢として、

1.  こちらのコードをrefactoringしてから使う
1.  `atcoder-tools` のコードをそのまま借りてくる
1.  こちらから `atcoder-tools` を呼び出す (向こうにプルリク投げるなども含む)

私がやるとすれば (1.) ですが、上手く交渉ができるなら (2.), (3.) もありです。

コード生成は面白そうかつ便利なのでつい足してしまったけれど、 `online-judge-tools` はサンプルの取得や提出といった基本的な機能にしぼりたいという気持ちがあります。`online-judge-tools` はライブラリとしても利用できるので、その上にコード生成専門のプログラムを (`atcoder-tools` の側と共同で) 構築できれば理想かもしれません。

**Comment by fukatani** [comment]
> online-judge-tools はライブラリとしても利用できるので、その上にコード生成専門のプログラムを (atcoder-tools の側と共同で) 構築できれば理想かもしれません。

この方針でユーザーにとって便利な状態（多くのサービスで多くの機能を受けられる）状態に持っていけたらいいですね。
話しかけてみたら意外といい方向にいくんじゃないでしょうか？（無責任）

**Comment by fukatani** [comment]
atcoder-tools作者様のブログを見ると、あちらはあちらで、online-judge-tools へのコード自動生成機能マージ
をちょっとやりたいみたいなことを言及してます。
http://kyuridenamida.hatenablog.com/entry/2018/12/27/091225

**Comment by fukatani** [comment]
時間があるときにatcoder-toolsを読み込んでみます。

**Comment by kmyk** [comment]
気合の入ったページが出きてた: https://kyuridenamida.github.io/atcoder-tools/#/quality/summary
こういうページが存在するということはやはりコード自動生成機能が中心で他はおまけなのだろうし、機能の単離の提案はしておくべきに見える

**Comment by kmyk** [comment]
した

**Comment by kmyk** [comment]
入力形式を自然言語でなくて `<pre>` とか `<code>` tag のあの形式で書く習慣があるのは AtCoder 以外だと現状では yukicoder と AOJ だけというのは書いておかないといけなさそう。
「URLをコピペしたら解析結果のコードを出力してくれるコンテスト中でも使える魔法のwebページ」みたいなのを用意して、利用のハードルを2段階ぐらい下げてやって普及させるなどする必要がある。

**Comment by kyuridenamida** [comment]
こんにちは。ダウンロードや提出通信周り+テストの部分をonline-judge-toolsに任せて、解析の部分をatcoder-toolsで使うというのは正直ありかなと思います。
実は過去にonline-judge-toolsの入力出力ダウンロード部分を使おうとしたんですが、python モジュールの一部を拝借してサンプルを任意のディレクトリ・サンプル名で出力する等ができなかったり、atcoderのクライアント部分だけをそのまま使おうとしてなんか失敗して諦めた経緯があるので(そのときはPRすればいいと思ったがなんか開発の疾走感を楽しみたかったため独自路線を行ってしまった)、もしかしたらお互いに感じていることは同じかもしれません。

そういう需要があるなら、コードジェネレーション部分だけを切り出したpython libraryを作ることを検討します。現状そんなにコードが複雑な絡んでいないはずなので。

ところで、僕はatcoder-toolsのコンテスト用のファイルを全部生成する機能とかが割と好きなのでそういうのをonline-judge-toolsでネイティブでサポートしてくれると嬉しかったりします。

**Comment by kmyk** [comment]
> そういう需要があるなら、コードジェネレーション部分だけを切り出したpython libraryを作ることを検討します。現状そんなにコードが複雑な絡んでいないはずなので。

これぜひよろしくお願いします。
online-judge-tools をライブラリとしての利用については、必要ならドキュメントの整備もします。


> ところで、僕はatcoder-toolsのコンテスト用のファイルを全部生成する機能とかが割と好きなのでそういうのをonline-judge-toolsでネイティブでサポートしてくれると嬉しかったりします。

これは少し検討させてください。
「コンテスト用のファイルを全部生成する機能」を好む人がいることは知っているのですが、ネイティブでのサポートをすべきかどうかは分かりません。特に atcoder-tools の提出機能を分離したライブラリないしプログラムを作るのだとすると、 online-judge-tools とその提出機能部分の両方の wrapper プログラムという形で外に出すべきだと考えています。
例えばそのようなものとして既に http://tatamo.81.la/blog/2018/12/07/atcoder-cli/ があります。

いずれにせよコンテストの列挙や問題の列挙をする機能は足します。(すでに別プログラムのために実装されているので)

**Comment by kmyk** [comment]
これ atcoder-tools があるので終了。コマンドも #359 で消えた
