### ISSUE TITLE
login: Yukicoder via Twitter or password

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#276]
私はGitHub経由のloginなので、これらは手元での動作確認すらできず実装が不可能です。なのでその方法でログインしてる人からのプルリク待ち

**Comment by fukatani** [comment]
私twitterでした。ひとまず、assigneesを私とします。（すぐには取り掛かれないので、奪ってもらっても構わないです。）

**Comment by fukatani** [comment]
twitterは規約でスクレイピングを禁止してるので、許可を得る必要があるとのことでした。
あとは、他のブラウザでログインしたcookieを、ユーザーがブラウザにエクステンションをダウンロードして手で取得してコピーして、という方法もあるかもしれません。ユーザーにかなり負担がありますが。

参考:
https://stackoverflow.com/questions/45261190/how-to-get-kaggle-competition-data-via-command-line-on-virtual-machine

**Comment by kmyk** [comment]
cookieからsession情報をコピペ」は良い方針だと思いました。私としてはこれを推したいです。
理由としては以下です。

-   ユーザ視点だと「GitHubやTwitterのパスワードを入力するのこわい」という気持ちがある (重要)
-   同時にすべての種類のログイン方法に対応できるので今後増えたときが楽
-   cookieの登録だけなのでメンテが容易。サイトの更新で壊れない


---

また、もしTwitter経由でログインするとしてもTwitterへの許可は不要だと思います。

「twitterは規約でスクレイピングを禁止してる」と言ったときは通常「TLのデータ取得をAPI経由せずにやるのをやめろ」の意味のはずです。実際、規約中の言及は以下のようなもので、クロールについての禁止となっています。

>   NOTE: crawling the Services is permissible if done in accordance with the provisions of the robots.txt file, however, scraping the Services without the prior consent of Twitter is expressly prohibited

一方で通常のブラウザからのアクセスは許可されているはずで、我々のアクセスも「エンドユーザからの手動での操作によって」行われるため、この点について許可を取る必要はないと思います。

**Comment by fukatani** [comment]
ありがとうございます。色々とわかっていないので、勉強になります。
ブラウザだってhtml解釈してるはずですものね。

cookieでのログインですが、普通にcookie.jarにコピペするだけでできました。
ドキュメントを書くので少々お待ちを。

**Comment by kmyk** [comment]
名前を戻していったん閉じたい
