### ISSUE TITLE
Add introduction on curated lists.

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#283]
ex. https://github.com/lnishan/awesome-competitive-programming

私自身のライブラリもawesomeに登録したことがありますが、多少流入が上がります。
リンクが増えれば検索エンジンの検索順位も上がるので、ユーザー数増やすには有効です。

https://github.com/slycelote/caide
というツールがすでに掲載されてますが、メンテがとまっているように見えているので、こちらはメンテされてたり、AtCoder対応してたり、ちゃんと説明できればonline-judge-toolsの掲載は可能と思います。スターも多いし。

よければPR出してみましょうか？

**Comment by kmyk** [comment]
これかなり良さそう。ぜひお願いしたいです。

**Comment by fukatani** [comment]
とりあえず、PR投げたのでクローズします。メンテナの方忙しそうなので、マージには時間かかるかもしれません。

**Comment by kmyk** [comment]
:+1:
ありがとうございます

**Comment by kmyk** [comment]
閉じると忘れるので開いておきたい

**Comment by kmyk** [comment]
https://github.com/lnishan/awesome-competitive-programming/pull/71

**Comment by fukatani** [comment]
無事、マージされました！

**Comment by kmyk** [comment]
めでたい。ありがとう
