### ISSUE TITLE
Generate scanner for rustlang

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#295]
欲しいので作っちゃおうかなーと。

**Comment by kmyk** [comment]
追加するのは賛成です。
しかしそのまま足すのは難しいので先にrefactoringが必要です。

**Comment by kmyk** [comment]
refactoringとかの話は #252 にまとめたい

**Comment by fukatani** [comment]
atcoder-tools宛のPR作成中で、ひとまずこちらでは作らないことにしたのでクローズします。
