### ISSUE TITLE
Yukicoder has two problem URL, but submit enable URL is only one.

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#300]
https://yukicoder.me/problems/no/361
https://yukicoder.me/problems/1016

の二つのURLから同一の問題にアクセスできる。
しかし、submitはhttps://yukicoder.me/problems/no/361からしか行えない。
エラーメッセージからデバッグできずハマる。

**Comment by kmyk** [comment]
:+1:

**Comment by fukatani** [comment]
クローズしたと思います。

**Comment by kmyk** [comment]
プルリクにぶらさげたコメントで `resolve #N` を書いてもだめで、一番上のコメントで書かないとだめということぽい
