### ISSUE TITLE
about the feature to prepare all files for a contest

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#316]
コンテスト用のファイルを一括生成する機能について (https://github.com/kmyk/online-judge-tools/issues/252 から)
需要はあるっぽいというのは知ってるのだけどどうすべきか分からないので検討をしたい。

しかし同時にディレクトリ構造の議論にも足を突っ込まないとだめ。現状は `-d` `--directory` のオプションを前提にするとディレクトリ構造についてはほとんど何も固定していません。たくさんの派閥が知られています。

以下は選択肢:

-   足すべき？
     -   「足すべき (下記のディレクトリ構造すべて対応すべき)」
     -   「足すべき (ディレクトリ構造はそこまで対応しなくていいよ)」
     -   「足すべき (設定ファイルをチューリング完全にすれば解決するよ)」
    -    「コンテスト中の問題を列挙する機能まで対応して残りは各自の `.bashrc` とかに書くべき」
    -    「コンテスト中の問題を列挙する機能まで対応して別プログラムとして切り出すべき」
    -    「やらなくていいよ」 
-    ディレクトリ構造どうする？
     -   「そもそもファイル保存しない派」 (Visual Studio 上とかで開発してて、問題を解くごとに全部消して書き直す)
     -   「すべてまとめる派」 (`arc001_a.cpp` の横に `cf123a.cpp`  や `srm686easy.cpp` が並ぶ)
     -   「コンテストサイトごとに分ける派」 (`atcoder/arc001_a.cpp` や `codeforces/123a.cpp` がある)
     -   「コンテストごとに分ける派」 (`atcoder/arc001/a.cpp` `atcoder/arc001/b.cpp` みたいな)
     -   「問題ごとに分ける派」 (`atcoder/arc001/a/main.cpp` `atcoder/arc001/b/main.cpp`)
     -   それ以外 (例えば「問題ごとに分けるけどコンテストでは分けない派」 (
 `atcoder/arc001_a/main.cpp` `atcoder/arc001_b/main.cpp`) 「問題ごとに分けるけどコンテストでもコンテストサイトでも分けない派」など)

一部のディレクトリ構造のサポートをするには「ソースファイルと問題URLやテストケースを紐付けるメタデータ」のサポートが必要。

**Comment by kmyk** [comment]
いちおうmention飛ばしておきます@kyuridenamida

**Comment by kyuridenamida** [comment]
色んな派閥がある(生成した後に後処理、たとえばCMakeList.txtを作りたいとか)のはそうで、冷静に考えて人々が有るものを繋ぎあわせて自由にラッパーを作れるようにインターフェイス整備を進めることに一票を投じます。
ディレクトリ生成とかラッパーに任せるべきな気がしてきました。

少なくともコンテストURLを与えるとコンテストに含まれる問題のURLとか問題番号(あれば)とかを出力する方法があったら各問題を`oj d`コマンドに流せるのでいい感じですね。
より厳密には、(コンテストURL) => コンテストの情報(コンテスト名, 各問題の問題名、問題番号、URLとか)を出力するモジュールが提供されると助かります。

**Comment by kmyk** [comment]
コメントありがとうございます。となるとやはりライブラリに徹する方向でいきます
