### ISSUE TITLE
the usage as a library

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#318]
-   [x] コンテスト列挙や問題列挙などの補助機能の追加
-   [ ] 関数名や例外などの仕様の検討と固定
-   [x] 内部向けの関数をきちんと private にする
-   [x] ドキュメントの整備
-   [x] 結合テストだけでなく単体テストも書く
-   [ ] semantic versioning

ちゃんとライブラリとして使えるようにするには、だいたいこれくらいかな？

**Comment by kmyk** [comment]
@kyuridenamida

**Comment by kmyk** [comment]
@fukatani 連絡: この整理をする用に issues の milestone の機能を使うことにしました。加えて [develop/v6.0.0](https://github.com/kmyk/online-judge-tools/tree/develop/v6.0.0) というbranchを切りました。

**Comment by kmyk** [comment]
過集中をやらかしてしまいすべて終わった

**Comment by kmyk** [comment]
@kyuridenamida ドキュメント https://online-judge-tools.readthedocs.io/en/develop/ と使用例 https://github.com/kmyk/online-judge-tools/blob/develop/tests/service_atcoder.py がまともになりました。なにか漏れがないか確認お願いします

**Comment by kyuridenamida** [comment]
いやまさかここまで異常な速度で整備が進むと思ってなくてかなりびっくりしてます・・・スピードに追いつけていない。素晴らしいです。ありがとうございます。

atcoderのやつしか見てないですがドキュメントかなりよさそうに見えます。
