### ISSUE TITLE
download, submit: catch some exceptions

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#365]
see #358

通常ありえる範囲の操作をしていてユーザから例外の文字列が見えるのは適当でないので、これはバグと言っていいはずです。

1.  存在してない問題を `download` すると例外
1.  ログインしてないときに `submit` すると例外
1.  存在しないファイルを `submit` すると例外

**Comment by fukatani** [comment]
あと、クッキーを全消去した後、ログインしようとしたら、http.cookiejar.LoadErrorになりました。
ユーザーがクッキーを編集して誤った時にこうなるかもしれません。

**Comment by fukatani** [comment]
Resolved by #453
