### ISSUE TITLE
Add a navigation to the documentation on README.md

### ISSUE THREAD

**Issue by kyuridenamida** [kmyk/online-judge-tools#374]
https://online-judge-tools.readthedocs.io/en/master/

このAPI DocumentへのリンクがREADMEのどこかにあったほうがいいと思います。ただし、開発者向けのDocumentであることもあり、どこにリンクを記載すべきかが分かりませんでした(上のほうか下のほうか)
Q&A内に「コマンドラインではなく、Python上から呼び出して使いたいがどうしたら良いか?」という質問を設け、そこに記載するというのはどうですかね。

**Comment by kmyk** [comment]
これ分かります。
ドキュメントのリンクが存在してないのは気付いてなかったので貼ります。
しかしQ&A内に書く程度ではおそらく不足なので、`Example` の下あたりに `How to use as a library` のような節を建てて具体例を書くべきに思います。そもそもPython上から呼び出して使うという発想のない人がかなり多いことが予想されるからです。

(ちなみに、想定されるユーザはほとんど誰も知らなさそうなので実質飛べないのと変わらないのですが、[![Documentation Status](https://readthedocs.org/projects/online-judge-tools/badge/?version=master)](https://online-judge-tools.readthedocs.io/en/master/) のようなバッチは一般にCIやドキュメントへのリンクになっており、実は現状でもここから飛べます)

**Comment by kmyk** [comment]
なお、まだ仕様が確定してない (`AtCoderProblem.get_rated_range()` の返り値の型は何であるべきか？ とか `AtCoderContest.get_contest_name()` の名前を `AtCoderContest.get_name()` したい気がするけどどうか？ とか) ので、誘導を書くのはもう少しまってほしいです。

**Comment by kyuridenamida** [comment]
>バッチは一般にCIやドキュメントへのリンクになっており

またひとつかしこくなりました。ありがとうこざいます。

> 誘導を書くのはもう少しまってほしいです。

正式に仕様が落ち着くまで待つ旨、了解です。
