### ISSUE TITLE
Make URL in AtCoder's submission response not dummy

### ISSUE THREAD

**Issue by kyuridenamida** [kmyk/online-judge-tools#376]
現状AtCoderに提出した後に返ってくる返り値として返ってくるSubmissionはDummySubmissionですが、これを最新の提出URLを含むものに置き換えるというのはどうでしょうか。もしよければ作業自体はこちらで行います。

コンテキストとして、AtCoder Toolsの内部でonline-judge-toolsを使おうとしているというのがあります。

**Comment by kmyk** [comment]
これが必要なのすごく分かります。こちらでも気付いていたのでちょうど先程 #373 で実装されました。

**Comment by kmyk** [comment]
行き違いになってしまってて申し訳ないです

**Comment by kyuridenamida** [comment]
手元でやったのと全く同じような実装になってて笑ってしまった
