### ISSUE TITLE
AtCoderへSubmit後の飛び先

### ISSUE THREAD

**Issue by peroon** [kmyk/online-judge-tools#392]
最近の oj はoj s した後の飛び先が
https://atcoder.jp/contests/agc005/submissions/xxxxxxx
・・・A

に変更になりましたね。以前はこちらでした。
https://atcoder.jp/contests/agc005/submissions/me
・・・B

Aの方が一意な提出先を指しているという利点はあるのですが
このページではリロードを何度か押してACか確認する必要があります。

Bでは自動更新されて見ているだけで結果が分かるので、
私はBに飛んでくれた方が使いやすいです。

ご参考になれば幸いです。

**Comment by kmyk** [comment]
要望ありがとうございます。
申し訳ないですが、こちらの回答としては、AからBに戻すのは難しいです。

まずBからAへ変えた理由についてですが、これに依存した派生ツールを作っている人のためにライブラリとして整備したためです。[AtCoderProblem.submit_code()](https://online-judge-tools.readthedocs.io/en/master/onlinejudge.service.atcoder.html#onlinejudge.service.atcoder.AtCoderProblem.submit_code) のようなメソッドの戻り値としてはAが自然であり、実際に要望もあります https://github.com/kmyk/online-judge-tools/issues/376 。
`oj s` の後の使いやすさで言うとAとBの差は好みに感じられ、ライブラリとしての使いやすさで言うとAでなければならないので、BからAに切り替えました。

可能な対応としては

1.  `oj s` の側だけBに戻す
1.  AとBを切り替えるオプションを作る
1.  AtCoderAのページでも自動リロードしてくれるようなオプションを作る
1.  AtCoder側にAのページでも自動リロードされるよう修正してもらう

それぞれの評価は以下のようになります

(1.) は可能ですが、A派とB派の比率が分からないので「はい、やります」とは言えません。例外的な処理を増やすとコードが汚れてバグが増えるので、A派の方が多いという証拠が必要です
(2.) は作っても毎回指定するのが面倒で誰も使わなさそうです。設定ファイルを作れば解決しますが、 https://github.com/kmyk/online-judge-tools/issues/315 のような議論があるのでしたくない
(3.) 書くだけだけどちょっと大変そう
(4.) (AtCoder社の側のリソースが余っていれば) これはすべての人にとって嬉しいはず

**Comment by peroon** [comment]
ご返信、ありがとうございます！
とても納得いたしました。

(4.)の要望をしてみます。
ありがとうございました。
