### ISSUE TITLE
list_problems() of onlinejudge.service.codeforces.CodeforcesService

### ISSUE THREAD

**Issue by kjnh10** [kmyk/online-judge-tools#435]
ドキュメントを確認しましたが存在していないようです。
追加予定などはありますか？？

**Comment by kmyk** [comment]
いつか実装する予定ではいます ([atcoder-tools](https://github.com/kyuridenamida/atcoder-tools) にこどふぉ対応してほしい意味でも必要なので) が、手が足りておらず時期は未定です。

@kjnh10 ところでこれはなにかに利用する予定が具体的にあっての質問ですか？ もしそうなら近いうちに実装しておきます。あるいはプルリクを投げてもらっても構いません。

**Comment by kjnh10** [comment]
oj dlなどが基本的にproblem単位だと思うので下記のようなscriptを自作してました。
https://github.com/kjnh10/pcm

その中でcontestのtop pageから全ての問題のURLを取得する処理を書いていたのですがここもonline-judge-toolsに任せられるなら任せた方が良いかと思いまして。。

基本的な処理の流れは移すだけなので後でプルリクを投げてみようかと思います。

**Comment by kmyk** [comment]
プルリクを投げてくれるなら助かります。

実装に関しては、 `CodeforcesService.list_problems()` を作るのはやりにくいはずなので、class `AtCoderContest` を参考にしながら class `CodeforcesContest` を作り、そこに method `CodeforcesContest.from_url(cls, url) -> Option[CodeforcesContest]` と method `CodeforcesContest.list_problems(self) -> List[CodeforcesProblem]` を書くのがよいと思います。
既に実装があるなら単にそれを移すのがよいですが、新規に書く部分があるなら公式の API https://codeforces.com/api/help を使うようにすると楽なはずです。

**Comment by kjnh10** [comment]
ありがとうございます。

それではプルリク作成してみますね。
また不明な点があればこちらで質問させて頂きますのでよろしくお願いいたします。
