### ISSUE TITLE
make tests runnable on Windows environment

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#440]
continued from #438

**Comment by fukatani** [comment]
https://github.com/kmyk/online-judge-tools/pull/455
でos :windowsを試したんですが、色々サポートされておらず、だめでした。

travisでやるなら、
language: genericでinstallブロックの中でPythonをインストールするようスクリプトを書けばできるかもしれません。

appveyorを使った方が無難な気はします。

https://github.com/RGF-team/rgf/blob/master/.appveyor.yml
こんな感じでymlの見かけはそこまでtravisとは変わらないです。

appveyor試してみましょうか？

**Comment by kmyk** [comment]
@fukatani AppVeyor を試すの、お願いします。上手く行ったら Travis CI から乗り換えましょう。 

(ところで念のため注意しておくと、現状はテストコードの側が Windows に対応しておらず、実行環境が正してくてもテストは落ちます。AppVeyor が上手く行ったらなんとか修正してみるつもりです)

**Comment by fukatani** [comment]
https://ci.appveyor.com/project/fukatani/online-judge-tools/builds/25694311/job/2yoj2lcc6dnbj88f

とりあえず、動きはしました。(Windows上でのテストのみ確認)
しかし、subprocessでojを使っているテストが全部落ちています。

**Comment by fukatani** [comment]
Windowsのコマンドプロンプトでojを動かす時って、どうやってるんでしたっけ？ご存知でしょうか？

**Comment by fukatani** [comment]
あ、もしかしてWSLじゃないと動かないのか、、appveyorはWSLはまだサポートしてないです。

**Comment by kmyk** [comment]
Windows 上で動かすには `python3 oj` (あるいは `python3.exe oj`) としてやればよいはずです。https://github.com/kmyk/online-judge-tools/pull/438 で生成されるようになった `oj.exe` を叩くこともできます。
WSL はただの仮想環境なのでこの文脈だと忘れて大丈夫です。

**Comment by kmyk** [comment]
とりあえずこの repo にも AppVeyor をインストールしました

**Comment by kmyk** [comment]
テストはだいたい動くようになりました。とりあえず可能なことは確認できたので、細部は後でやります
https://ci.appveyor.com/project/kmyk/online-judge-tools/builds/25709360/job/tnhi4o8bnw9dkk3d

**Comment by fukatani** [comment]
@kmyk 
timeとかファイルパスとか細かい所はありますが、いけそうですね :smile: 
(あまりなにもやっていませんが、)お願いいたします :baby:
