### ISSUE TITLE
make portable executable for Windows

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#459]
#440 ができそうなので次は単一の `oj.exe` を作って配布したい。

PyInstaller (https://github.com/pyinstaller/pyinstaller) はいけそうだけど、クロスコンパイルができないので Windows 環境が必要ですこし手間。
PyOxidizer (https://github.com/indygreg/PyOxidizer) はクロスコンパイルができてよいのだけど `__file__` が使えないのでだめぽい。

**Comment by fukatani** [comment]
appveyor上でコンパイルして、コンパイルされた.exeをテストし、デプロイはそこで生成された.exeをartifactとしてダウンロードするということが一つ方法としてはできそうです。

**Comment by kmyk** [comment]
@fukatani https://github.com/kmyk/online-judge-tools/pull/462 が終わったので、これを任せたいです。

`pyinstaller --onefile onlinejudge._implementation.main` みたいにすると `dist/main.exe` にいい感じのバイナリが生成されることは確認しています。これが `oj.exe` という名前でうまく GitHub 上から落とせるようになれば完璧です。

**Comment by kmyk** [comment]
@fukatani `pyinstaller --onefile onlinejudge._implementation.main` これは間違いで `pyinstaller --onefile onlinejudge/_implementation/main.py` などが正しかったです。ごめんなさい

**Comment by kmyk** [comment]
TODO: https://github.com/kmyk/online-judge-tools/pull/471#issuecomment-509625838 より

- [ ] `oj.exe`のテストを書く
- [ ] アップロードが確認されたら、Windows向けのインストールガイドを書く

**Comment by kmyk** [comment]
メモ: 現段階では `oj.exe` は https://ci.appveyor.com/project/kmyk/online-judge-tools/builds/25847591/job/cvxivsig1f3g37bj/artifacts などから落とせる
