### ISSUE TITLE
notifications about releasing

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#466]
バージョンを上げた際の Twitter 上での告知は、これまでは (@fukatani さんをコラボレータに追加する前からの慣習として) ずっと私がしていました。しかし以下の2点により、積極的に https://twitter.com/fukafukatani 経由での告知をした方がよいように思います。

1. ユーザから @fukatani が認識されていなさそう。これは貢献に対する報酬の観点で不適切である
1. 複数人での開発が行なわれているのはユーザの安心感に寄与する。なので積極的に知らせていきたい

@fukatani よさそうなら、とりあえず次回からしばらくの間任せたいです。どうですか？
なお、任せる内容には「そもそも告知をするかどうか」も含めて考えています。たとえば「細かいバグ修正1個だけだししなくていいや」みたいなやつです

**Comment by fukatani** [comment]
全然いいですよーと言ってた思ってたんですが、返事してませんでした！
しばらくやってみます！

**Comment by fukatani** [comment]
閉じます！
