### ISSUE TITLE
Don't finish submit command until browser closed if browser was not opened.

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#477]
submitコマンドでbrowserオープンが有効になっているとき、

1) ブラウザがすでに起動していた場合
タブを開き速やかに、submitコマンドは終了

2) ブラウザが起動していなかった場合
ブラウザが起動するが、ブラウザが閉じるまでsubmitコマンドは終わらない

という挙動になっていることに気づきました。
`subprocess.check_call([browser, submission.get_url()], stdin=sys.stdin, stdout=sys.stdout, stderr=sys.stderr)`が終わりません。

browserはChromeを使っています。

**Comment by fukatani** [comment]
仕様なのかもしれないですが、、
コマンドラインで使っている分にはあまり困らないんですけど、APIとして叩いているときは戻ってこないので少し困ります。

**Comment by kmyk** [comment]
この挙動だと困るだろうなあというのは分かるのですが、あまり対応したくないです。理由として

1.  利便性を置いておいて設計や挙動としての正しさを考えたとき、明らかに現状が正しい
    web ブラウザは Chrome や Edge だけでなく、 w3m のようなテキストブラウザや Uzbl のようなタブを持たないブラウザもあります。現在の挙動を変更すると特にテキストブラウザが利用できなくなります。
2.  設計の正しさを捨ててまで対応するほどの利便性があるとは思えない
    Chrome を使っているような人ならたいてい常に Chrome を起動し続けているはずです。実際に困ることは少ないはずです。

もちろんテキストブラウザが使えなくなって困る人もかなり少ないはずですが、不便さが同程度なら挙動の素直さを優先したいです。API として叩くのであればなおさらで、典型的な場合の使いやすさのための修正を繰り返すと機械にとって扱いにくいものになりがちです。

---

とりあえずの対処としては、以下のような shellscript を書いてそれを呼び出してほしいです。

``` sh
#!/bin/sh
google-chrome "$@" &
```

現状はオプションで指定されたブラウザを実行ファイル名として扱っていますが、単にコマンドとして扱う (つまり `sh -c 'google-chrome "$@" &'` のような指定を許す) ように修正するのがとりあえず妥当な落とし所であるように思います。

**Comment by fukatani** [comment]
設計の考え方はわかりました。納得しました。
これだけが原因ではないのですが、online-judge-toolsからではなく、私が開発しているIDEからブラウザを開くようにしました。

というわけで私としても対応は不要です。
