### ISSUE TITLE
Question about API usage

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#479]
今、私が自作しているIDEで、

submit→submit statusをIDE上にpopupするfeatureをAPIを使って実装しようとしているのですが、
コンテスト中にAtCoderSubmission.from_url()すると、
これって、IDE側で`with utils.with_cookiejar(utils.new_session_with_our_user_agent(), path=args.cookie) as sess:`を使うのが正しい設計でしょうか？
![test](https://user-images.githubusercontent.com/8858287/61185450-a54a6e80-a694-11e9-99d5-4469e67b6035.png)

**Comment by fukatani** [comment]
get_statusにsessionを渡すのかしら

**Comment by kmyk** [comment]
AtCoder 等へのログイン状態を IDE 側で管理するなら、自分で `request.Session` を生成して `submission.get_status(session=...)` のように渡してください。

ログイン状態を `oj` コマンドと同期させたいなら現在は `with utils.with_cookiejar(utils.new_session_with_our_user_agent(), path=...) as sess:` を使うしかないでしょう。
ただしこれは通常のインターフェースでなく、仕様外の内部実装の詳細に依存してしまうことに注意してください。つまり突然動かなくなっても文句が言えない使い方になってしまっています。インストールする online-judge-tools のバージョンを固定した方がよいでしょう。
正当な方法で利用したい場合は、そのような機能を公式に提供するようなプルリクを投げてください。

**Comment by kmyk** [comment]
(ところで submit status を popup で通知するのおもしろい気がする。web 上では yukicoder とかもやってるけど IDE 側でやる発想はなかった)

**Comment by fukatani** [comment]
アドバイスありがとうございます！やりたいことができそうです。

ブラウザとIDEをスイッチするのが嫌で、
競技プログラミング専用IDEを定義するなら、それは競技プログラミングで行われる全て(問題閲覧、実装、テスト、デバッグ、提出結果確認)をIDEで完結するべきだと考えてます。統合競争環境、ともいえます。

そういう考えで作られているIDE(もしくはそれらの拡張)はまだあまりないので、そういう意味ではブルーオーシャンで面白い領域なのかなと思っています。

そして、それを実現しやすくするためにojがどうあるべきか、というのも面白そうですね。
online-judge-tools開発、という視点でどうすべきか考えてみます。
