### ISSUE TITLE
provide internal utilities as documented one

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#480]
現状では `onlinejudge._implementation.utils` の中などにある関数のいくつかは外側に公開されるべきです。実際に利用する際に困る (例: https://github.com/kmyk/online-judge-tools/issues/479) ので整備されるべきです。

具体的には以下が公開されるとうれしそう。しかし無闇にすべて公開しても不要な制約と破壊的更新が増えるだけなので、実際に必要性が生じたものに限るようにはしたい。

-   session と cookie の周辺
-   提出言語の推測の機能
-   logging の周辺
-   `test` サブコマンドの機能のいくつか

**Comment by fukatani** [comment]
開発ガイド書きたいです！

- APIを使うと、どんな機能が実現できるのか、というのsubmit resultの取得が例にして説明したり
- session渡さないとコンテスト中にget_statusが動かないので注意

とか、そういうコンテンツです。

（そしてゆくゆくは誰かにVS CodeとかIntelliJあたりのプラグイン開発してほしい）

**Comment by yosupo06** [comment]
session系が欲しいです　具体的な用途としては問題単位ではなくコンテスト単位で管理するラッパーを使用する時、どうしてもdispatch.contest_from_url(...).list_problems()をやりたくなり、開催中のコンテスト(のうち一部だけかも？少なくとも多くの企業主催のコンテスト)ではlist_problems()にloginが必要　といった用途です

**Comment by kmyk** [comment]
要望のあったものはすでに提供されてるし、#719 があるから閉じてよい
