### ISSUE TITLE
Test result is AC if output file doesn't exist.

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#483]
例えばsample3.inがあってsample3.outがないとき、test結果がACになってしまいます。
これって仕様でしたっけ？

**Comment by kmyk** [comment]
はい。仕様です。

意図としては TLE や RE でないことを確認するためにあります。
具体的には、入力がすべて最大値付近のケースを手でひとつ書いて置いておく、乱数生成された入力に対して AC / WA の判定を解法の実装内の assert でやってしまう、のような形で利用されます。

**Comment by fukatani** [comment]
そういうことですか。

ところで、私がテストケースを足そうとしてsample3.inを作ったのにsample3.outを保存し忘れて、
でもテスト結果はACになってしまったということがありました。
これを回避するために、
1) ACではなく、No Errorみたいなstatusにする
か、
2)警告かメッセージを出す

みたいな変更を行いたいと思うのですがどうでしょう？

**Comment by kmyk** [comment]
その事故と問題意識は理解できますが、そのような変更はやりたくないです。

やりたくないと感じる原因を考えてみたところ、これは競プロにおけるテストに関する立場の差から来ているはずです。
「期待される出力との比較をしていないので AC ではない」というのは「サンプル入出力を試すことのみがテストである」に近い立場からの発想だと思います。そしてこの立場は不十分であると考えています。

競プロを行う上では単純な比較のみならず「`assert` による実行時の検証」「Clang の sanitizer などによる実行時診断」「大量にランダム生成された入力によるストレステストやファジング」までをテストだと見なすべきというのが私の立場です。将来的には「ランダムケースの自動生成」まで視野に入れています。このような立場として、提案された変更は以下のような理由で反対です。

1. 「TLE や RE にならず正常終了すること」は期待される結果であり、テストが成功した証拠である。なので status は AC でよい
1. 単に出力を比較する以外の利用法は推奨されるものなので、警告がでるべきではない

---

妥当な対案を見つけることはできず、現状維持が最もましだと考えています。
`AC` という表記が狭義の AC でないというのは真です。 `No Error` という status は不満ですが、たとえば `OK` のような表記 (`AC` と同じ緑色の文字) への変更なら問題ないように思います。しかしこれはテストケースの保存忘れのような事故を防ぐことにはほぼ役立たないでしょう。
他にも「 対応する出力がない入力ファイルがあるときにエラーにするオプションを作る」「エディタの swap ファイルを使って保存忘れを検証する」などが考えられますが、どちらも不十分です。

**Comment by kmyk** [comment]
close じておきます。必要なら再 open してください
