### ISSUE TITLE
Can't get a name of a contest without penalty

### ISSUE THREAD

**Issue by hamayanhamayan** [kmyk/online-judge-tools#487]
素晴らしいライブラリをありがとうございます。
使っていて、自分で修正した箇所がありますので、プルリクを出そうかと思っています。
developとmasterのどちらにプルリクを出せばいいでしょうか。
以下、問題と原因の概要です。

---

# 現象

このコードでAssertionErrorが発生する。  

```python
AtCoderContest.from_url('https://atcoder.jp/contests/otemae2019').get_name('ja')
```

# 原因

このコンテストはペナルティなしのコンテストであり、パースに失敗している。  
AssertionErrorが発生しているのは、以下の部分。

https://github.com/kmyk/online-judge-tools/blob/7a321991171fd12aff169864a53a42ffafa54e9c/onlinejudge/service/atcoder.py#L250-L253

**Comment by fukatani** [comment]
@hamayanhamayan 
バグ報告ありがとうございます！

今修正していただいたブランチのベースがmasterならmasterでPR立ててみてください。developはそれに対してrebaseするのがよさそうです。

**Comment by hamayanhamayan** [comment]
@fukatani 
PR発行しました！

**Comment by kmyk** [comment]
マージされたので閉じます。

@hamayanhamayan 丁寧なバグ報告とプルリクありがとうございました。
