### ISSUE TITLE
download: failed on https://atcoder.jp/contests/agc036/tasks/agc036_b

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#507]
https://atcoder.jp/contests/agc036/tasks/agc036_b のパースに失敗する。
失敗を検出できずに素通りさせてしまってたのが、 #461 のあたりで例外を吐いて停止するようになったのでひとまずは安心。しかしそもそもきちんと動作してほしい。

**Comment by fukatani** [comment]
Already resolved by #554 .
