### ISSUE TITLE
AtCoder Sumbission: Status = NG is not supported.

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#510]
https://atcoder.jp/contests/ttpc2019/submissions/7408739

NGというステータスがありました。同じコードをもう一度提出したら起きなかったので、
まれにおきるなにかのようです。

**Comment by fukatani** [comment]
https://atcoder.jp/contests/abc074/glossary?lang=ja
仕様に無いのでAtCoderに問い合わせます。

**Comment by fukatani** [comment]
とりあえず、仕様らしいです。NGが出た時は連絡すればリジャッジするよと言ってました。

**Comment by kmyk** [comment]
`NG` を処理したいことはないはずだし、仕様についても確認が取れました。なのでひとまず閉じておきますね
