### ISSUE TITLE
freeze the versions of linters

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#535]
In the current settings, CI sometimes fails when linters are updated.
This should be avoided.

---

> 依存ライブラリはバージョンを止めろ、そして頻繁に上げろ、とgoogleの人がこの前PyCon JPで言ってました。

https://github.com/kmyk/online-judge-tools/pull/533#issuecomment-535584500

**Comment by fukatani** [comment]
I quoted from [this session](https://pycon.jp/2019/schedule/?sessionId=201).
This session is about how to ensure nondeterministic behavior in test.
He introduced `pip-compile` command, but we don't have to use pip-compile in this situation.
