### ISSUE TITLE
Discuss specification for sample downloading if sample already exists.

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#571]
> I think that we should not add options like --overwrite, because it will easily cause mistakes.
For example, if there is three samples (sample-1.in, sample-1.out, …, sample-3.out) and oj download --overwrite rewrite only two of them (sample-1.in, …, sample-2.out), then a very confusing state happens. oj test will never succeed since there is an irrelevant sample (sample-3.in, sample-3.out).
Of course, also the current behavior, just skipping, has asimilar issue.
I think that just failing is better if samples with the same name are found.

I agree with @kmyk .

1) We should not continue to support `--overwrite`.

2) Default behavior should be changed and terminate if file exists.

3) By the way, is `--force` option is useful?
If user specified `force` option, remove test directory first and start download.
It equals `rm -r test/; oj download URL`.

**Comment by fukatani** [comment]
ex. `git checkout -f` and `rm -f` is not different from our situation.
They only omitted one command, and their are little dangerous.
But they are useful and often I use them.

For `--force` option, I want to listen user voice.

**Comment by kmyk** [comment]
closed by #575
