### ISSUE TITLE
AtCoder now show Exec Time even if it's TLE

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#586]
As far as I remember, AtCoder didn't show the Exec Time of submissions if they are TLE. However, it seems to be changed to show now. (e.g. https://atcoder.jp/contests/tricky/submissions/119944)
This breaks CI (e.g. https://travis-ci.org/kmyk/online-judge-tools/jobs/605305911)

**Comment by kawacchu** [comment]
@kmyk 
This is being discussed in #582, #583 .

**Comment by fukatani** [comment]
resolved by #583
