### ISSUE TITLE
Invalid cookie causes crash.

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#600]
異常なCookieが紛れ込むとojが使えなくなります。
私が確認したのは以下のような、versionがNoneのcookieです。
このようなCookieが現れた時、cookieを消せばいいですが、そのようなメッセージを発した方がいいかもしれません。

```
Set-Cookie3: mc="XXXXXX"; path="/"; domain=".quantserve.com"; path_spec; domain_dot; expires="2020-09-08 14:39:56Z"; HttpOnly=False; version=None
```

```
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/_implementation/utils.py", line 101, in with_cookiejar
    session.cookies.load()  # type: ignore
  File "/usr/lib/python3.5/http/cookiejar.py", line 1784, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "/usr/lib/python3.5/http/cookiejar.py", line 1959, in _really_load
    (filename, line))
http.cookiejar.LoadError: invalid Set-Cookie3 format file '/home/ryo/.local/share/online-judge-tools/cookie.jar':
```

ただし、発生条件がよくわからないです。私の使い方が特殊なせいかもしれません。私以外の人は起きてなさそうなので、、
競プロIDEは付属のブラウザでめぐったサイトのセッション情報をojのcookieに書き込むことで、ブラウザでのログイン情報を使ってojでもログイン済とするようなことをやっていて、その中で`with_cookiejar`を叩いており変なCookieを保存してしまったかもしれません。
dispatchが成功するサイトでのみcookieを保存などはやっていますので、あらゆるサイトの情報が集まるわけではないのですが。

**Comment by fukatani** [comment]
ojもセレニウムのCookieを保存するようになったので、もしかしたら同様なことは起きるかもしれません。

**Comment by kmyk** [comment]
いまのところあまり oj で対処すべきには見えないように思います。他の人からの報告があるか、具体的な再現方法が分かるまで様子を見たいです。

通常の利用の範囲内で発生するなら対応 (どうせログインにしか使ってないので `cookie.jar` をぜんぶ消して続行とかでもよさそう) したいですが、もしこれが「内部で使われているファイルを勝手に弄って破損させると oj が動かなくなる」でしかないなら現状の動いている状態に手は入れたくなさがあります。

**Comment by fukatani** [comment]
そうかもしれません。私の環境でも個々半年ほどで二回しか起きてなくて、いつのまにか紛れ込んだ形でCookieが差し込まれるのでよくわかりません。
私の方のポカかもしれないので様子見します。（競プロIDEで対処することも可能なので、ここでやってくれないと困るというわけではありません。）

**Comment by fukatani** [comment]
私がojをmutexなしで複数プロセスで叩いていたのが原因のようです。。一旦クローズします。

**Comment by kmyk** [comment]
排他制御してないとファイルが壊れうるのは正しいですが、だとしてもそれが原因で値に `None` が紛れ込むのはあまりなさそう (ないこともないけど) に思えます。不思議。
もし単に oj を同時に複数実行しても再現するようなら (排他制御の追加という形で) 対策したい気がします。

**Comment by fukatani** [comment]
うーん、正確にはCookie周りのエラーが複数種類起きてたんですが、たしかにversion=Noneは再現しませんでした。だから排他制御が原因かわかりません。
他のエラーというのはcookieに書き込んだ瞬間に別のプロセスでは読みこもうとして、その瞬間は正常なcookieファイルじゃないから読めないというエラーでした。
