### ISSUE TITLE
invite @kawacchu to be a maintainer

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#601]
@kawacchu oj のメンテナをすることに興味はありませんか？
良いプルリクをいくつも書いてくれているため誘っています。
メンテナになると「プルリクに対しレビューをしマージをする権限」が渡され、それを行使することが期待されます。
もちろん断わってもらっても構いません。よろしくお願いします。

---

プロジェクトにとっての利点は主に以下のふたつです:

- 開発の効率が上がる。oj はもう機能を積極的に追加する段階は過ぎていて保守性や信頼性を上げていきたくて、このために「誰であれコードのマージには他のメンテナによるレビューと承認が必要」という規則を維持したい。しかしメンテナがひとりでも忙しくなると更新が止まるのはよくないので、もうひとりメンテナがほしい
- 議論をする上で @kmyk と @fukatani だけであると owner である @kmyk の意見が通りがちでよくないが、これが改善される。3 人いれば多数決もできるようになる

@fukatani には既に Twitter の DM (公開の場所でやると反対を主張しにくいので) で確認をして、賛成ということでした。

**Comment by fukatani** [comment]
メンテナになる利点は、
PRのマージ過程(レビューコメント、コントリビューターとのディスカッション)やメンテナ間の意見のコンフリクトやその調整、CI/CD、リリース作業、告知などを通したコミュニティの拡大といった一つの(小ぶりではありますが)プロジェクトの開発サイクルの全てに立ち会い経験が深まるといったところかと思います。
もちろんやれるところやりたいところをやってもらえれば、私達としては助かります。

ちなみにコストとしてどれだけお仕事が発生するかというと、10月はHacktoberfestもあり、私も張り切ってたんですけど実際はそこまでPRは来ません。

**Comment by kawacchu** [comment]
@kmyk @fukatani 

Thank you for inviting me!
I'm interested in maintaining this repository to help contestants. I'll accept your offer!
But I'm still OSS beginner, and I want your help in some situation.


And... let me think about making my AtCoder ID public due to privacy issue.

**Comment by kmyk** [comment]
@kawacchu Thank you for acceptance!
It's no problem that you are an OSS beginner. Everyone is a beginner at first, and we'd like to help you.
I've sent the invitation from the GitHub's settings, so please accept it: https://github.com/kmyk/online-judge-tools/invitations .

In terms of your AtCoder ID (or, Codeforces ID), of course, you can keep it secret.
However, I would like to show your rating somewhere, if possible. This project handles users' passwords and submissions in some contest sites, so trust from (end-)users is required. And the easiest way to earn trust in the competitive programming community is by showing your rating (it's better to higher).

**Comment by kawacchu** [comment]
Accepted!

> In terms of your AtCoder ID (or, Codeforces ID), of course, you can keep it secret.
However, I would like to show your rating somewhere, if possible. This project handles users' passwords and submissions in some contest sites, so trust from (end-)users is required. And the easiest way to earn trust in the competitive programming community is by showing your rating (it's better to higher).

I changed my AtCoder ID and make my ID public.
AtCoder: [kawacchu](https://atcoder.jp/users/kawacchu)
