### ISSUE TITLE
test: UnicodeDecodeError is thrown when the outputs contain non-Unicode

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#602]
When the program to be tested prints non-Unicode strings, `oj` raises `UnicodeDecodeError`.
This often happens if you write strange languages, e.g. code golf with perl, brainfuck, etc.

This happens on both of WSL and native Ubuntu.

``` console
$ oj --version
online-judge-tools 7.3.0

$ cat main.py
#!/usr/bin/env python3
import sys
sys.stdout.buffer.write(b'\xff')

$ oj t -c 'python3 main.py'
[*] 10 cases found

[*] sample-1
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/oj", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge/_implementation/main.py", line 297, in main
    run_program(namespace, parser=parser)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge/_implementation/main.py", line 276, in run_program
    test(args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge/_implementation/command/test.py", line 218, in test
    history += [test_single_case(name, paths['in'], paths.get('out'), args=args)]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge/_implementation/command/test.py", line 142, in test_single_case
    answer = (info['answer'] or b'').decode()  # type: str
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by kawacchu** [comment]
Replicated in my laptop(Ubuntu18.04).

I'm sorry but I have no domain knowledge about code golf.
So I can't imagine such situation (submission using non-Unicode)...
Could you show me a submission related to this issue? Thanks.

**Comment by kmyk** [comment]
For example, a code `a=-1;main(){write(1,&a,3);}` of C language prints non-Unicode.

Of course, as far as I know, there are no problems whose correct answer contains non-Unicode. But wrong answers which we may write print non-Unicode.
About the example above, if it were `a=4407873;main(){write(1,&a,3);}`, it would print an ASCII letters `ABC`. We sometimes use such techniques, and print non-Unicode unintentionally.

**Comment by kawacchu** [comment]
I got it now.

I think `UnicodeDecodeError` is kind message for users in order to prevent them from WA.

We can change the code to 
```
answer = (info['answer'] or b'').decode(encoding='utf-8', errors='replace')
```
but I can't judge if that modification is good or not...

**Comment by kmyk** [comment]
I feel `errors='replace'` is nice.
I rarely want to check the value is whether `\xff`, `\xfe`, or others. Rather, I want oj to run without exceptions and to show in what cases the program fails.

**Comment by kawacchu** [comment]
Certainly, we can guess something wrong with code by seeing _mojibake_ output.
 
@fukatani How about you?

**Comment by fukatani** [comment]
errors='replace' looks good to me.
Anyway, we should handle it as WA, instead of Exception.

**Comment by kawacchu** [comment]
OK! Let's using `errors=replace`.
