### ISSUE TITLE
grant permissions for CI

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#607]
現状は AppVeyor の CI の rebuild ボタンを押せるのが @kmyk だけらしい。これを @fukatani や @kawacchu にも押せるように設定したい。

これは AppVeyor の team 機能を使えばできそうに見える。ところでこれをするには AppVeyor 上での ID (メールアドレス) が分からないとだめなので、これを教えてください >> @fukatani @kawacchu 

---

Travis CI についてはレポジトリの collaborators の設定を読んでいい感じにしてくれているらしいので問題ないと認識しています (正しいですか？)。

**Comment by fukatani** [comment]
twitterでDM送りました。
TravisはRestartできるけど、なぜかはわからない。

**Comment by kmyk** [comment]
とりあえず設定してみました。
Travis CI で restart できるのはリポジトリ側の設定を参照する仕様になっているからだと思います。

**Comment by kawacchu** [comment]
I'll send my mail address via twitter.

**Comment by kmyk** [comment]
@kawacchu 設定をしました。
正しく設定できているかはこちらからは分からないので、よさそうなら issue の close を、だめそうなら再設定の要求をお願いします。

**Comment by kawacchu** [comment]
:ok:
