### ISSUE TITLE
Too many output in Circle CI

### ISSUE THREAD

**Issue by yosupo06** [kmyk/online-judge-tools#609]
https://circleci.com/gh/yosupo06/Algorithm/31 などを見てもらうと早いのですが、Circle CI上でojを使用するとstripが働かず全てを出力します。

shutil.get_terminal_size()が`os.terminal_size(columns=0, lines=0)`を返し(https://circleci.com/gh/yosupo06/Algorithm/30 )、それが _implementation/utils.py -> snip_large_file_content.snip_char_basedのfont[-char_in_line * tail:]をバグらせているのではないか、と予想しています。

もし想定した挙動だったらすいません(手元で動かすとstripして、CI上ではstripしないというのはらしい挙動に思えたので)

**Comment by kmyk** [comment]
報告ありがとうございます。想定外の挙動です。
CI 上だとしてもこれはよくないので修正します。
