### ISSUE TITLE
Generate input bug?

### ISSUE THREAD

**Issue by farhannz** [kmyk/online-judge-tools#614]
the generate input command saved output instead of the input

```
[*] random-000
[x] generate input...
1
A
asd.
4
A
!
[x] time: 7.308625 sec
input:
=============
Review Barang
=============
+Kode   : A
>Nama   : asd
>Jumlah : 3
=============

[+] saved to: test\random-000.in
```

**Comment by farhannz** [comment]
or did i do it wrong?

**Comment by kawacchu** [comment]
@farhannz 
Thank you for sending issue!

To clarify this problem, please tell me command and generator file like below?

```
$ oj --version
online-judge-tools 7.3.0

$ cat generate.py
#!/usr/bin/env python3
import random
N = random.randint(1, 100)
W = random.randint(1, 10000)
print(N, W)
for _ in range(N):
    v = random.randint(1, 1000)
    w = random.randint(1, 1000)
    print(v, w)

$ oj g/i ./generate.py

[*] random-000
[x] generate input...
[x] time: 0.041610 sec
input:
1 4138
505 341

[+] saved to: test/random-000.in

...

[*] random-099
[x] generate input...
[x] time: 0.036598 sec
input:
9 2767
868 762
279 388
249 673
761 227
958 971
589 590
34 100
689 635
781 361

[+] saved to: test/random-099.in

```

**Comment by kawacchu** [comment]
And I want to know your OS(Windows, Mac OS, GNU/Linux...).

**Comment by farhannz** [comment]
> @farhannz
> Thank you for sending issue!
> 
> To clarify this problem, please tell me command and generator file like below?
> 
> ```
> $ oj --version
> online-judge-tools 7.3.0
> 
> $ cat generate.py
> #!/usr/bin/env python3
> import random
> N = random.randint(1, 100)
> W = random.randint(1, 10000)
> print(N, W)
> for _ in range(N):
>     v = random.randint(1, 1000)
>     w = random.randint(1, 1000)
>     print(v, w)
> 
> $ oj g/i ./generate.py
> 
> [*] random-000
> [x] generate input...
> [x] time: 0.041610 sec
> input:
> 1 4138
> 505 341
> 
> [+] saved to: test/random-000.in
> 
> ...
> 
> [*] random-099
> [x] generate input...
> [x] time: 0.036598 sec
> input:
> 9 2767
> 868 762
> 279 388
> 249 673
> 761 227
> 958 971
> 589 590
> 34 100
> 689 635
> 781 361
> 
> [+] saved to: test/random-099.in
> ```

Ahhh i see, so the compiled answer can't be the generator, ah my bad than.
