### ISSUE TITLE
download: no samples found in AtCoder tenka1_2014_qualA_e

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#618]
`oj d` fails for <https://atcoder.jp/contests/tenka1-2014-quala/tasks/tenka1_2014_qualA_b> and <https://atcoder.jp/contests/tenka1-2014-quala/tasks/tenka1_2014_qualA_e> without making corrupted files.

嘘を出力するわけではないのであまり深刻ではないが、AtCoder 側の JavaScript はきちんと認識しているのでたぶん直せるし直しておくべき

``` console
$ oj d https://atcoder.jp/contests/tenka1-2014-quala/tasks/tenka1_2014_qualA_e       [x] problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/tenka1-2014-quala/tasks/tenka1_2014_qualA_e'): https://atcoder.jp/contests/tenka1-2014-quala/tasks/tenka1_2014_qualA_e
[x] load cookie from: /home/ubuntu/.local/share/online-judge-tools/cookie.jar
[x] GET: https://atcoder.jp/contests/tenka1-2014-quala/tasks/tenka1_2014_qualA_e
[x] 200 OK
[x] save cookie to: /home/ubuntu/.local/share/online-judge-tools/cookie.jar
[x] append history to: /home/ubuntu/.cache/online-judge-tools/download-history.jsonl
```

**Comment by kawacchu** [comment]
報告ありがとうございます。
たしかに上記の問題に対して`oj d`は期待された結果を出力していません。
このコンテストの問題のHTMLを確認したところ、A問題、B問題、E問題のHTMLは想定されていませんでした。


具体的には、
[ABC003D](https://atcoder.jp/contests/abc003/tasks/abc003_4)のように`prettyprint linenums`がCSSに用いられていた場合、HTMLが以下のような構造になっていると仮定していました。

```
<div class="part">
    <h3>入力例 1</h3>
    <section>
        <pre class="prettyprint linenums">
SAMPLE
</pre>
    </section>
</div>
```

しかし、今回の問題では以下のように、`<h3>`と`<section>`が逆になっているため、`tag_plus`で正しいSampleと認められず弾かれてしまいます。

```
<div class="part">
    <section>
        <h3>入力例1</h3>
            <pre class="prettyprint linenums">
SAMPLE
</pre>
    </section>
 </div>
```

さらに、A問題は`<h3>`タグ内で`<var>`タグを使用していることもバグの原因になっています。

**Comment by kawacchu** [comment]
1つ目は`<h3>`タグまで貪欲に`previous_sibling`を実行することで解決できます。
2つ目は`<h3>`タグに`utils.parse_content`を実行することで解決できます。
このように変更しても既存の問題のパースが新たに壊れることはありません。

なので、この方針で実装しようと思うのですが、いかがでしょうか。

**Comment by kmyk** [comment]
その方針でも解決はできるので悪くはなさそう (プルリクが来たらマージはする) ですが、なんとなく筋が悪い気がします。
というのも、今回のものは AtCoder 本体が使用している JavaScript はサンプルの認識に成功しているためです。これに倣って以下の `h3+section pre` を判定していることろを消して `pre.prettyprint` を用いる形で解決したいです。これは変更量が大きいので不安ですが、AtCoder 公式に併せておいた方が長期的には安全に思われます。

ちなみに申し訳ないことに、現状なぜ AtCoder の JavaScript に従った実装になっていないかは記憶にないです。当時は `Copy` ボタンが存在していなかったか、単に下手をやったかのどちらかでしょう。

https://github.com/kmyk/online-judge-tools/blob/00adee25ed70b53bbe535f2772d4758022205348/onlinejudge/service/atcoder.py#L653-L654

---

## 参考

### 現状の実装

https://github.com/kmyk/online-judge-tools/blob/00adee25ed70b53bbe535f2772d4758022205348/onlinejudge/service/atcoder.py#L636-L685

### AtCoder 側の JavaScript <https://atcoder.jp/public/js/contest.js?v=201911110917>

``` javascript
  // copy button
  if (document.queryCommandSupported('copy') && (typeof PRINT === 'undefined')) {
    $("#task-statement h3+pre").each(function(i){
      var id = "pre-sample"+i;
      $(this).attr("id", id);
      var h3 = $(this).prev('h3');
      h3.append(' <span class="btn btn-default btn-sm btn-copy" tabindex="0" data-toggle="tooltip" data-trigger="manual" title="Copied!" data-target="'+id+'">Copy</span>');
      $(this).before('<div class="div-btn-copy"><span class="btn-copy btn-pre" tabindex="0" data-toggle="tooltip" data-trigger="manual" title="Copied!" data-target="'+id+'">Copy</span></div>');
    });
    var cnt = 0;
    $('pre.prettyprint').each(function() {
      var pre_id = "for_copy"+cnt;
      var btn_html = '<div class="div-btn-copy"><span class="btn-copy btn-pre" tabindex="0" data-toggle="tooltip" data-trigger="manual" title="Copied!" data-target="'+pre_id+'">Copy</span></div>';
      $(this).before(btn_html);
      $(this).addClass('source-code');
      var for_copy_html = '<pre id="'+pre_id+'" class="source-code-for-copy"></pre>';
      $(this).after($(for_copy_html).text($(this).text()));
      cnt++;
    });
  }
```

**Comment by kawacchu** [comment]
kmykさんの方針はメンテナンスコストの点で優れているように感じます。
変更量は大きいですが、最新のコンテストには直接影響を及ばさないと思われるので、問題ないと思います。

@kmyk 私はこの方針の実装に自信がないので、assignしても構いませんか。

**Comment by kmyk** [comment]
自分に assign しました。
