### ISSUE TITLE
Is name utils appropriate for public API?

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#644]
APIとして公開するなら、名前がもうちょっとわかりやすくてもいいかなと。
例えば、`oj_session`とか、`session_util`とか。
幸い、リリースされてないからまだ間に合う？

**Comment by fukatani** [comment]
@kmyk 見解あれば、、

**Comment by kmyk** [comment]
具体的にはどの部分の名前をどう変更することを提案していますか？
`onlinejudge.utils.with_cookiejar()` などの関数名ですか？ `onlinejudge.utils` という module の名前ですか？

**Comment by fukatani** [comment]
そうです。`onlinejudge.utils`というモジュール名です。
例えばドキュメントの[インデックス](https://online-judge-tools.readthedocs.io/en/master/py-modindex.html)に掲載されるわけですが、モジュール名にsessionという言葉が入っていれば、「おっ、セッションに関する機能があるのか」と思ってくれるんじゃないかなと。

**Comment by kmyk** [comment]
その方向での名前の変更は、単に名前の変更だけでなく module の分割と細分化をも意味しています。そして無闇な細分化は管理が面倒になるので、どちらかと言えば避けたいです。

### 詳細

公開すべき内部関数は session 関連だけではなく「内部で使ってるディレクトリの情報」「ファイルから提出用の言語選択 ([link](https://github.com/kmyk/online-judge-tools/blob/8e753cf90c69127df9e8bc8d332276886876c175/onlinejudge/_implementation/command/submit.py#L165))」なども含むと考えています。実際に現在の `onlinejudge/utils.py` では `onlinejudge.utils.user_config_dir` のような定数も公開されています。
`onlinejudge.session_utils` のような名前の module にするならこれら他の機能は `onlinejudge.path_utils` や `onlinejudge.language_utils` のような個別の module に分けることになります。そしてたとえば「現在の `onlinejudge.utils.default_cookie_path` はどの module に入れればよいのか？」のような面倒が出てきます。これはあまりうれしくないです。

ただし細分化せず `onlinejudge.utils` にまとめる方向にも問題はあります。現状では `onlinejudge.dispatch` という module があるがこれとの整合性はどうなんだという問題と、この手の曖昧な名前は雑に機能が増やされて肥大化しがちという問題です。

**Comment by fukatani** [comment]
`default_cookie_path`くらいはセッションの仲間みたいなものですし(雑)、うまく名前をつけられる気もしますが、`user_config_dir`は無理がありますね。仕方ないのかな。

あと全然関係ないですが、`user_config_dir`ってどういう使い方が想定されているのでしょうか？

**Comment by fukatani** [comment]
少なくとも、今は肥大化してないのでパッケージの細分化に手を付けるのはやめましょう。

**Comment by kmyk** [comment]
`user_config_dir` はたぶん使ってないですね。必要になるまで消しておいた方がよさそう

**Comment by kmyk** [comment]
#636
