### ISSUE TITLE
Should we submit Python code with PyPy by default?

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#656]
そもそも定数倍が不安な問題を Python で書かないのでよく分かりません。有識者たのむ

**Comment by kawacchu** [comment]
多くの contestant は Python3 と PyPy3 の両刀使いという認識です。
私は基本 Python3 で, 困ったときに PyPy3 にしていました。
AtCoder では現状 PyPy3 が Python3 の完全な上位互換ではないため流派が分かれるところですね。

**Comment by kmyk** [comment]
こういうときは Python で橙になったプロであるところの [maspy](https://atcoder.jp/users/maspy) さんの提出を見るのが正解だと思うんですが、基本的に Python + やばそうなときだけ PyPy という感じでした。なので変える必要はなさそう
