### ISSUE TITLE
Remove split-input subcommand

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#664]
テストされていないので。
（サポート続けるべき機能ですよね？←使ったことがない）

**Comment by kmyk** [comment]
> サポート続けるべき機能ですよね？

私はたまに使うんですが、たぶん私以外に使ってる人ほぼいなさそう。なので消してもいいと思っています。わざわざテストを書くのもわざわざ消すのもどちらも面倒なので放置されています。

**Comment by kmyk** [comment]
よく考えたら「消してもいいかも」という議論が発生するような機能はたいして重要でないのでさっさと消すべきなんですよね。
ということで、しばらく様子を見て何も異論がなさそうなら消しましょう。

**Comment by fukatani** [comment]
kmykさんが使ってないなら迷いなく消したいところですが、、

ただ、基本的にはテストして自信を持ってサポートするか、消すかの二択ではあると思います。
