### ISSUE TITLE
support yukicoder token

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#672]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr"><a href="https://t.co/KXCa8x4WC1">https://t.co/KXCa8x4WC1</a><br><br>ヘルプページに「ログインしてないと使えない機能をAPIとして使いたい」を追記しました</p>&mdash; yukicoder公式アカウント (@yukicoder) <a href="https://twitter.com/yukicoder/status/1225783039491375104?ref_src=twsrc%5Etfw">February 7, 2020</a></blockquote>

verify helper から yukicoder が利用できるとうれしいので対応したい。
実装は単に `--yukicoder-token` みたいなオプションを用意するのがよさそう。`YUKICODER_TOKEN` みたいな環境変数を設定させてそれを読むのは一般には自然だが、現状の online-judge-tools は他にはまったく環境変数を見ないので一貫性が損われる。

「token を発行して適切に設定する」をエンドユーザにやらせるのは要求が大きすぎて良くない (例: verify helper のドキュメント生成機能を使えている人は半数ぐらいしかいない) のだけど、妥協案としては妥当。いままではログイン方法が多すぎ (これ自体はとてもよいこと) なためログイン自動化も無理で詰んでたので、可能になっただけでもありがたい。

cc: @beet-aizu

**Comment by beet-aizu** [comment]
大体調べ終わったのであとは実装すればできそうです

以下調べたことのメモ：
/problems/{問題ID}/file にpostでリクエストを投げる
結果がそれぞれjsonで帰ってくる

入力一覧
{"action" : "index", "which" : "in" }

出力一覧
{"action" : "index", "which" : "out" }

個別のファイル
{"action" : "get", "which" : "in", "file" : "00.txt" }

CSRF tokenはトップページにアクセスして var csrf_token = の行をパースするのが楽そう

**Comment by beet-aizu** [comment]
抜けてた

problems/no/{問題No} と problems/{問題ID} の対応の取り方がよくわからん

**Comment by beet-aizu** [comment]
main/body/content に data-problem-id として入ってた　これも自動化した方がいいのかな

**Comment by beet-aizu** [comment]
ツイートボタンの横に ProblemId: で書いてありますね（目がついてなかった）

**Comment by kmyk** [comment]
実はダウンロード部分はすでに実装済みです。以下のように実行すれば (login には webdriver を追加でインストールする必要があるけど) システムケースは取れます。なので、HTTPリクエストヘッダーになにかを設定するあたりだけやれば終わるはず。

``` console
$ oj login https://yukicoder.me/
$ oj download --system https://yukicoder.me/problems/no/880
```

https://github.com/kmyk/online-judge-tools/blob/e311e7cf1ed6cfb91fa8cb381ad5cdb06a57ef33/onlinejudge/service/yukicoder.py#L259-L270

**Comment by beet-aizu** [comment]
1 download_system_casesの*を*argsに書き換える
2 problemがyukicoderproblemのインスタンスかどうか見る
2は設計としてよくないと思うんですが1も微妙な気がします
