### ISSUE TITLE
Support Google Code Jam / Kick Start

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#683]
They are important since GCJ is one of the three largest contests (GCJ, FHC, and TCO).

Now they have two formats.

1. new format: https://codingcompetitions.withgoogle.com/kickstart/round/0000000000050edd https://codingcompetitions.withgoogle.com/codejam/round/0000000000051707
2. old format https://code.google.com/codejam/contest/10224486/dashboard

**Comment by kmyk** [comment]
Kick Start Round A 2020 は Mar 22 2020, 04:00 なのでこのあたりまでに実装する

**Comment by kmyk** [comment]
間に合いませんでした

**Comment by fukatani** [comment]
とはいえ、バグ修正が優先ですし、kmykさんのおかげでかなり良いリリースだったんじゃないでしょうか。
今後のRoundで間に合えば嬉しいですけど。

**Comment by kmyk** [comment]
> Google Kick StartのRound Bが二週間後なので、それまでに #715 が間に合えばいいかと。

https://github.com/kmyk/online-judge-tools/issues/716#issuecomment-608992711
