### ISSUE TITLE
--side-by-side is badly broken

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#684]
出力が100行以上あるテストケースに対しほぼ全行間違っているプログラムでテストを走らせたところ、以下のような表示を得ました。「ほぼすべて間違っている」という状況なのに、自然に解釈すると「先頭4行だけが間違っている」あるいは「そもそも4行しかない」としか読めない出力になっています。
この壊れ方はよくないです。うっかり勘違いして時間を溶かす人が出てくる種類の壊れ方になっています

@fukatani 直してください。もしすぐには直せないようなら `--side-by-side` オプションをひとまず無効化するのでそう伝えてください

<img width="1193" alt="Annotation 2020-02-21 065932" src="https://user-images.githubusercontent.com/2203128/74982595-c0296080-5477-11ea-88de-a27bc5c99df5.png">

**Comment by fukatani** [comment]
全ての行を出すと時間がかかってしまう、ということだったので、私の中での仕様通りでした。
全ての行を出力するか、他にも間違っている行はあるよとメッセージを出すかかな。
