### ISSUE TITLE
--side-by-side option confuses when some lines are deleted

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#688]
左に出ている数字は、上の画像では実際の出力の行番号になっており、下の画像では期待される出力の行番号になっています。これらの行番号は明らかに異なるものであり、それを混同した表示は適切ではありません。

<img width="619" alt="Annotation 2020-02-23 223820" src="https://user-images.githubusercontent.com/2203128/75113041-3521b380-568d-11ea-8b64-39a126a518e4.png">
<img width="619" alt="Annotation 2020-02-23 223933" src="https://user-images.githubusercontent.com/2203128/75113055-64382500-568d-11ea-8e70-cf37d96ac2ad.png">

**Comment by fukatani** [comment]
明日直します。

**Comment by fukatani** [comment]
何をすべきかわかってきた
