### ISSUE TITLE
warn or tell it if spaces exist before newlines

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#698]
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">どうみてもサンプルと同じ出力なのにWAになっててなんもわからん</p>&mdash; 海豹もどき＠春からNullReferenceException (@azarashi_uni) <a href="https://twitter.com/azarashi_uni/status/1237547402719932418?ref_src=twsrc%5Etfw">March 11, 2020</a></blockquote>

<https://atcoder.jp/contests/abc101/submissions/10748017>

---

改行の前に空白文字があると気づけなくて詰む。
そんな出力をする方が悪い (`diff` コマンドも同様の出力をする) けれど、なかなか気づくの難しそう。「コンテスト中に発生するとレートが下がる」の条件を満たすため、バグです。

たとえば

``` console
$ xxd test/sample-1.out
00000000: 310a 320a 330a 340a 350a 360a 370a 380a  1.2.3.4.5.6.7.8.
00000010: 390a 3139 0a
```

が期待されているところに

``` console
$ ./a.out < test/sample-1.in | xxd
00000000: 3120 0a32 200a 3320 0a34 200a 3520 0a36  1 .2 .3 .4 .5 .6
00000010: 200a 3720 0a38 200a 3920 0a31 39          .7 .8 .9 .19
```

と出力すると、

![2020-03-11-150732_1139x830_scrot](https://user-images.githubusercontent.com/2203128/76387443-4ddada80-63aa-11ea-8647-cc0c760f2e13.png)

のような表示になってやばい。

**Comment by fukatani** [comment]
これは私もやりました。side-by-sideにしたらスペースがハイライトされて気づきました。
