### ISSUE TITLE
Persistent cache/ in successive CI builds?

### ISSUE THREAD

**Issue by GaurangTandon** [kmyk/online-judge-tools#707]
I have noticed that in every CI build, for example [this](https://travis-ci.org/github/AnimeshSinha1309/AlgorithmsNotebook/jobs/663825603), there are a lot of:

```
[x] GET: https://X.Y/Z
[x] 200 OK
```

calls which probably take up the majority of the build time. Is it not possible to persist the `cache/` directory across successive CI builds (so redundant GET calls are avoided)?

**Comment by fukatani** [comment]
Thank you for opening issue!

Travis CI itself supported cache feature.
But in addition, you have to edit `.travis.yml` to use cache.

```
cache:
  directories:
  - /path/to/cachedir
```

Please see https://docs.travis-ci.com/user/caching/#arbitrary-directories

**Comment by fukatani** [comment]
BTW, there is useful tool for verifying your library on github CI.
https://github.com/kmyk/online-judge-verify-helper

@kmyk Does online-judge-verify-helper support caching test cases?

**Comment by kmyk** [comment]
@fukatani No, online-judge-verify-helper doesn't support caching test cases yet.
But results of tests are cached. After tests for a file succeeded, the same tests for the same file are skipped until the file is modified.

**Comment by fukatani** [comment]
"file" means any implementated library?

If so, in many situations, we edit part of library files. Therefore, test time is not so long.

**Comment by GaurangTandon** [comment]
Hi, thanks for your helpful responses! I will look into the other repo you linked to. Does it have any other significant advantage over oj-tool apart from generating awesome documentation like [this one](https://beet-aizu.github.io/library/library/combinatorics/partition.cpp.html)?

**Comment by kmyk** [comment]
One of the advantages of online-judge-verify-helper is the "bundle" feature.
We would like to write our libraries with multiple files, but most judge services require single `.cpp` files to submit. The "bundle" feature solves this problem. It converts `.cpp` files and `#include`-ed many `.hpp` files into the single `.cpp` file.
