### ISSUE TITLE
logが複数行に渡って出力される。

### ISSUE THREAD

**Issue by kjnh10** [kmyk/online-judge-tools#709]
以下のコードを実行するとBはログが２回重複、Cはログが３回重複して吐き出されます。
これは想定通りの挙動でしょうか？

```
from onlinejudge._implementation.main import main as main
import subprocess

main(['download', "https://atcoder.jp/contests/abc159/tasks/abc159_a"])
subprocess.run(['rm', '-rf', 'test'])
main(['download', "https://atcoder.jp/contests/abc159/tasks/abc159_b"])
subprocess.run(['rm', '-rf', 'test'])
main(['download', "https://atcoder.jp/contests/abc159/tasks/abc159_c"])
```

**Comment by fukatani** [comment]
mainの中で、

```
log.addHandler(log.logging.StreamHandler(sys.stderr))
log.setLevel(log.logging.INFO)
```
を読んでおり、main関数をコールした数だけ、Handlerが足されてしまいます。
想定していた挙動かというと、うーん、main関数をimportしてAPIとして叩かれるということを想定していませんでした。

既にHandlerが存在していた場合、重複して追加しないみたいなことをすべきなのかしら？

ひとまず、
`log.handlers.clear()`
をmainの後に毎回叩くようにすれば、重複しなくなると思います。

**Comment by kjnh10** [comment]
なるほど。

ひとつのコンテンストの問題を全てとってくる処理を実装していてそこで使用していたのですが、
subprocess.run()なりに任せた方がよい気がしますね。

回答ありがとうございました。
