### ISSUE TITLE
oj test should also compile the file or "pre-invocation directives"

### ISSUE THREAD

**Issue by GaurangTandon** [kmyk/online-judge-tools#710]
This feature is exclusive to compiled languages.

When I am in a hurry in the contest, I don't want to first compile my code and then run `oj test`. In the hurry of wanting to see the results, sometimes I might as well forget to compile and run `oj test` (that will inadvertently run the old executable).

So, two things:

1. if there is reasonable support for implementing this feature, please do. If I can help, please let me know and I will try my best.
2. if there isn't support, at least warn the user that the modification time of source file is newer than the executable is.

-----

You could generalize this feature out by allowing `pre` invocation commands, which can be run before `oj test` does. This way you don't need to worry about each language separately, and users will also be able to specify their favorite compilation commands!

**Comment by kmyk** [comment]
The feature exists in your shell. For example, please use `g++ main.cpp && oj test` to run `g++ main.cpp` as a pre command.

**Comment by fukatani** [comment]
Thank you for your suggestion!

In my opinion, some Python programmers wants to check their script by `mypy`, some C++ programmers wants to check their executables are newer than source file, other language programmer want to check their linter.

Such "language specific" features seems not scope of `oj`.


If typing a command every time is troublesome, I think writing a shell script can be a solution.

```sh
g++ ./main.cpp -fsanitize -and-many-options && oj test -c -y -w 0 "./a.out";
rm ./a.out  #  erase executable every time
```

**Comment by kmyk** [comment]
@fukatani, your answer doesn't make sense.
As @GaurangTandon wrote, the suggestion is *NOT* language-specific.

> This way you don't need to worry about each language separately, and users will also be able to specify their favorite compilation commands!

---

Also, you should add shell aliases or shell functions in a config file like `.bashrc`, rather than writing shell scripts.

**Comment by GaurangTandon** [comment]
Alright, sure. I'll add in a bash alias!
