### ISSUE TITLE
Removing the delays from oj submit, or oj submit --force?

### ISSUE THREAD

**Issue by GaurangTandon** [kmyk/online-judge-tools#711]
It it possible to remove the `sleep(3.0)` and the `Are you sure?[y/N]` from the submission feature. It is sometimes quite frustrating when you've solved a simple problem and know that the solution is correct.

So, could we add:

1. `--force/-f` flag in `oj submit` command
2. boolean option in some `.ojconfig` file

telling `oj submit` to not add the extra delay.

(sorry for spamming with issues, but I just started using this tool for and it's working awesomely :) thanks for it!)

**Comment by fukatani** [comment]
Please try `oj submit -y -w 0`.
You can change wait time by -w option.

**Comment by kmyk** [comment]
Some people ask the same question.

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">online-judge-tools、デフォルトではsubmitのwait時間が三秒になっているので、これを短くすればタイムが縮んで順位が上がるという知見を得た。私の場合日立コンであと2秒速かったら4位上がる。</p>&mdash; fukatani (@fukafukatani) <a href="https://twitter.com/fukafukatani/status/1239546663783419904?ref_src=twsrc%5Etfw">March 16, 2020</a></blockquote>

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">online-judge-toolsの提出前に強制的に3秒スリープするのって変えられないんですか</p>&mdash; こどふぉ埋める (@andoreiji11) <a href="https://twitter.com/andoreiji11/status/1244555888473460736?ref_src=twsrc%5Etfw">March 30, 2020</a></blockquote>

**Comment by kmyk** [comment]
By the way, I don't recommend removing the delays and confirmations, because they are "safety devices". Of course, you can earn 3 seconds by removing them. But when you make mistakes to submit and get penalties, you lost much more time (e.g. 5 minutes in AtCoder).
