### ISSUE TITLE
コミット権限の整理

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#713]
@kawacchu しばらくあなたの活動を見ていないので、あなたのコミット権限をいったん無効化しておこうと思います。よいですか？

**Comment by kawacchu** [comment]
はい。私から申し上げるべきでしたが、コミット権限を無効化していただきたいです。

**Comment by fukatani** [comment]
@kawacchu 
容赦なきリストラ :sob: いや、卒業？
これまでのコミッターおよびコントリビュータとしての貢献、ありがとうございました。
少し残念ですが、PRでもなんでもいただけたら、またいつでも暖かく歓迎します :smile:

**Comment by kmyk** [comment]
無効化しました。

@fukatani さんに「容赦なきリストラ」などと書かれてしまっていますが、私としては「メンテナやるの飽きちゃったのかな、残念だなあ」ぐらいの気持ちです。また暇になったらコミット権限を要求してください。

**Comment by kmyk** [comment]
まあメンテナが数ヶ月音沙汰なしぐらいならよくあることなんですが、いま #687 のような話を進めていて、不明な理由で議論に参加できない人はいったん明確に議論の外にいるというフラグを立てておきたい気持ちがありました。

**Comment by kawacchu** [comment]
@kmyk @fukatani 
しばらく食い扶持のことを優先しようと思います。
色々と軌道に乗ったら1 contributorとしてまた参加します。
