### ISSUE TITLE
Travis CI failed to cooperate with GitHub

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#716]
ref #712 #714 #715 

Travis CI と GitHub の連携が上手くいっておらず、CI が実質落ちる。
Travis CI の公式の forum の thread: https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798

我々の取れる選択肢:

1. Travis CI 側が直るのを待つ
    1. プルリクのマージも待つ
    1. Travis CI はしばらくは使わないことにしてプルリクのマージをする
2. 設定が legacy なのが悪いらしいので <https://travis-ci.org> から <https://travis-ci.com> へ migrate する
3. GitHub Actions に乗り換える

他はどれも面倒なのでひとまず (1.) の (i.) で考えています。

**Comment by fukatani** [comment]
Google Kick StartのRound Bが二週間後なので、それまでに #715 が間に合えばいいかと。

**Comment by kmyk** [comment]
AppVeyor も含めての GitHub Actions への移行、そのうちやります

**Comment by fukatani** [comment]
Google Code Jam Round がApr 11でした。
https://codingcompetitions.withgoogle.com/codejam/schedule

厳しそう？

**Comment by kmyk** [comment]
@fukatani  #718 は緊急度高め (壊れててもレートは下がらないが、不快感は大きい) だし AppVeyor の CI は動いてるので、しばらくの間 Travis CI は無視してマージする運用にしてもいいかなと考えています。これはよさそうですか？

**Comment by fukatani** [comment]
そうですね、ローカルでのテストが通ってればいいと思います。

**Comment by kmyk** [comment]
Travis CI が成功していなくても merge できるように設定変更しました。かわりに AppVeyor が必須になります。

**Comment by fukatani** [comment]
> As I stated earlier, the incident concerns reaching the GitHub API rate limit. That issue is resolved, thanks to the (temporary) raise granted by GitHub.

There are other cases where we fail to post statuses for various reasons (chief among them is having tokens being out of sync). These may still occur, but these would have occurred even before the incident.


直った、と言っているように見えます。

**Comment by kmyk** [comment]
よかった (ところでそれどこからの引用ですか？)

**Comment by fukatani** [comment]
公式のThreadでのTravis CIチームの発言です。もし直ってなければ報告したほうがよいのでは。

**Comment by kmyk** [comment]
Travis CI はまだ動いてないんですが、「直した。それでも動かないなら元々あった別の原因だ」って言ってるし、いずれにせよ解決策は自明に migrate なので報告はいらないでしょう。
