### ISSUE TITLE
Add more tests about sample cases which are fixed after the contest started on AtCoder

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#726]
#724

> バージョンを上げて更新する前に追加で安全装置をいくつか足しておきた (「サンプルを修正しました」系が書かれている問題をいくつか探してきてテストを足す、任意個の `<p>` を許す仕様だけど高々 1 個にする、`<p>` の中に 修正 みたいな文章が含まれているものに限る、など) ですが、このプルリク自体はよいものなのでマージします。保険の追加は @kotatsugame がやってくれてもよいし、やらないなら私がやっておきます。

https://github.com/kmyk/online-judge-tools/pull/724#issuecomment-614021875

**Comment by kotatsugame** [comment]
何をするにしても、やはりサンプル修正のテストが1つきりでは方針を定めかねるので、とりあえずそれを探すことにしてみます。Twitterで募集をかけるなど……

**Comment by kmyk** [comment]
簡単に検索 https://www.google.com/search?q=site:atcoder.jp+%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB+%E4%BF%AE%E6%AD%A3 してみたところ、今回の変更で修正されそうなものは次のひとつしか見つけられませんでした。

- https://atcoder.jp/contests/pakencamp-2019-day4/tasks/pakencamp_2019_day4_h

(ほとんど存在してないようなら、`<p>` を無視するとかでなくて正解サンプル埋め込みが最適だったかもしれません)

**Comment by kotatsugame** [comment]
これまで見つかった2つは両方h3+preのタイプなので、それだけpとbrを無視する方法も考えられますが、結局p+pre.literal-blockのタイプのものを最初にチェックしないとならないんですよね。このチェックの順番を変えたのもかなり怖い

**Comment by kotatsugame** [comment]
僕はサンプル埋め込みに直すのに異存はないです。その場合は_find_sample_tagsではなくてもっと外の部分を変更するのですか？

**Comment by kmyk** [comment]
> その場合は_find_sample_tagsではなくてもっと外の部分を変更するのですか？

はい。そうなると思います。(本質部分のコード量を減らしたいので、埋め込み部分は外に弾き出したい)

ただし、埋め込みは埋め込みで問題が多いので、結局どうするのかはもう少し考えさせてほしいです。

**Comment by fukatani** [comment]
本筋とは関係ありませんが
パース部分を変更した時は、今までAtCoderで出題された問題全てに対して変化がないことを確認したほうがいいかもしれませんね。（変化してても改善されてるならOK。）
yukicoderでやったときは問題noをインクリメントしつつサンプルパースしたものをテキストにダンプしてdiffを取ればできました。

**Comment by fukatani** [comment]
https://www.google.com/search?sxsrf=ALeKk0064mUI2V3DApNLwil5f9jEE-3IBw%3A1586992618092&ei=6pWXXrSmBZr_wAPmxIHYDg&q=site%3Aatcoder.jp+%E3%83%AA%E3%82%B8%E3%83%A3%E3%83%83%E3%82%B8&oq=site%3Aatcoder.jp+%E3%83%AA%E3%82%B8%E3%83%A3%E3%83%83%E3%82%B8&gs_lcp=CgZwc3ktYWIQA0oOCBcSCjExLTEwMGcxMjlKCggYEgYxMS00ZzhQyvwgWKefIWD7kCJoAXAAeACAAdMBiAHMCpIBBTUuNi4xmAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwi0w4yayOvoAhWaP3AKHWZiAOsQ4dUDCAs&uact=5

リジャッジでも検索したほうがいいかも。サンプルじゃなくてテストケースを修正したと表現している問題もあり。

**Comment by kotatsugame** [comment]
とりあえずやってみています。AtCoder の場合は https://kenkoooo.com/atcoder/resources/contest-problem.json から引っ張ってくるのが一番簡単ですね。古いページも新しいページも問題文は変わっていないようなので、新しいほう（atcoder.jp/contests/...）だけチェックします。

**Comment by kotatsugame** [comment]
https://atcoder.jp/contests/iroha2019-day3/tasks/iroha2019_day3_d
https://atcoder.jp/contests/kupc2015/tasks/kupc2015_i
https://atcoder.jp/contests/kupc2016/tasks/kupc2016_d
https://atcoder.jp/contests/kupc2019/tasks/kupc2019_i
https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_h
https://atcoder.jp/contests/s8pc-3/tasks/s8pc_3_h
https://atcoder.jp/contests/s8pc-4/tasks/s8pc_4_h
https://atcoder.jp/contests/ttpc2015/tasks/ttpc2015_i
https://atcoder.jp/contests/xmascon16midnight/tasks/xmascon16_b
https://atcoder.jp/contests/xmascon16/tasks/xmascon16_b
https://atcoder.jp/contests/xmascon16noon/tasks/xmascon16_b

これだけ結果が変わる問題がありました。今から内容を見てみます。
コンテスト参加者でないと確認できない問題文が3問ありました。

**Comment by kotatsugame** [comment]
ttpc2015_i 以外は全部インタラクティブとかマラソン形式の問題ばかりで、むしろ中途半端にサンプルを検出してしまって困ったことになります……
あと kmyk さんが指摘してくださった https://atcoder.jp/contests/pakencamp-2019-day4/tasks/pakencamp_2019_day4_h なんですが、これは入力例の代わりに「入出力例」と書かれていて、どちらにせよサンプルは検出できませんでした。

**Comment by kmyk** [comment]
@kotatsugame 調査ありがとうございます。この差分の情報はとても助かります。

> ttpc2015_i 以外は全部インタラクティブとかマラソン形式の問題ばかりで、むしろ中途半端にサンプルを検出してしまって困ったことになります……

ということなので、誤検出を増やすデメリットの方が多そうで #724 を revert するのが最適に思えてきました。どう思いますか >> @kotatsugame 
(もっと早くに私がこのことに気付いておくべきでした。ごめんなさい :bow: )

また埋め込みについても、一見すると楽でよさそうなのですが、よく考えたら割に合わない気がしてきました。メンテが必要で継続性がない (私と @fukatani が明日突然失踪すると機能しなくなる) 上に、コンテスト本番で動かないためです。

**Comment by kotatsugame** [comment]
> 誤検出を増やすデメリットの方が多そうで #724 を revert するのが最適に思えてきました。

同意します。埋め込みを諦めるのも妥当かなあという気持ちです。AtCoderだけ手間暇かけるのも美しくない（？）ですし……

**Comment by kmyk** [comment]
@kotatsugame revert するプルリクを作るのお願いしたい。よいですか？

**Comment by kotatsugame** [comment]
以前の実装をコピーして戻せばよいですか？また、追加したtestも消しますか？

**Comment by kmyk** [comment]
以前の実装をコピーして戻せばよいです。ただし、それをする用のコマンド `git revert` があるので可能ならこれを使ってください (revert 対象がマージコミットなので `-m 1` のようなオプションがたぶん必要です)。
追加したテストは残しておいてください。コーナーケースなのでとりあえず残しておくと役に立ちます。コミットをひとつ指定してそれだけ利用してくれるコマンド `git cherry-pick` を使うのがおすすめです。もちろんそのままではテストが落ちるので [@unittest.expectedFailure](https://docs.python.org/ja/3/library/unittest.html#unittest.expectedFailure) を指定して (+ プルリクの URL だけとかでよいので簡単にコメントを書いておいて) ください。

**Comment by kotatsugame** [comment]
多分できたと思います。 #727

**Comment by fukatani** [comment]
@kmyk 
kotatsugame さんがやってくださった差分確認法はパース部をいじる時に毎回やったほうがいい気もするのですが、サンプルパース結果をダンプするスクリプトをリポジトリに入れるのはどうでしょうか？

**Comment by fukatani** [comment]
![test](https://user-images.githubusercontent.com/8858287/79455508-eeff2580-8027-11ea-990d-05b9753e977e.png)

PRのrevirtはGithub上のボタンから一発でできるので、これが一番楽です。参考まで。

**Comment by kotatsugame** [comment]
初めて知りました。ありがとうございます。
@kmyk #727 を close したあと、テスト追加だけの pull request をもう一度作成するほうがチェックの手間が少ないのかもしれません

**Comment by kmyk** [comment]
@kotatsugame diff を見れば同じなのでこのままで大丈夫です https://github.com/kmyk/online-judge-tools/compare/f2c17336fbdfe10981babc6227443d0d40e9420b...f881e2ed4947b7eec176c5aa9e12ca4a8c888c04

**Comment by kmyk** [comment]
@fukatani 

> kotatsugame さんがやってくださった差分確認法はパース部をいじる時に毎回やったほうがいい気もするのですが、サンプルパース結果をダンプするスクリプトをリポジトリに入れるのはどうでしょうか？

とてもわかる。
ただし #719 でやる JSON 形式の出力を比較するのがよいはずで、実装はしばらく後回しにしたい

**Comment by kmyk** [comment]
この issue も閉じてよいはず

@kotatsugame ありがとうございました。本体は結局 revert になってしまったけど、エラーメッセージは確実に改善されました。
